on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          activate-environment: grinch
      - run: conda --version
      - run: grinch -h
      - run: pip install .
      - run: conda env create -f environment.yaml
      - run: conda activate grinch
      - run: grinch -h
