on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install wheel
      - run: pip install .
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          environment-file: environment.yaml
          activate-environment: grinch
      - run: conda info
      - run: grinch -h
