on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install .
      - run: conda env create -f environment.yaml
      - run: conda activate grinch
      - run: grinch -h
